name: Frontend deployment
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get source code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci
            
